window.EPLData = (() => {
 const api='https://site.api.espn.com/apis/site/v2/sports/soccer/eng.1';
 const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
 const color=t=>t?.color?`#${t.color}`:'#77736a';
 function dateRange(){const d=new Date(),f=x=>x.toISOString().slice(0,10).replaceAll('-','');let a=new Date(d);a.setDate(d.getDate()-50);let b=new Date(d);b.setDate(d.getDate()+80);return `${f(a)}-${f(b)}`}
 function normalize(event){const c=event.competitions?.[0], teams=c?.competitors||[],home=teams.find(x=>x.homeAway==='home'),away=teams.find(x=>x.homeAway==='away'); if(!home||!away)return null; const completed=event.status?.type?.completed===true,live=event.status?.type?.state==='in'||event.status?.type?.name==='STATUS_IN_PROGRESS',scored=completed||live;return {id:event.id,time:new Date(event.date),home:clean(home.team.displayName),away:clean(away.team.displayName),homeId:String(home.team.id||''),awayId:String(away.team.id||''),homeAbbr:home.team.abbreviation,awayAbbr:away.team.abbreviation,homeLogo:home.team.logo||home.team.logos?.[0]?.href||'',awayLogo:away.team.logo||away.team.logos?.[0]?.href||'',homeColor:color(home.team),awayColor:color(away.team),homeScore:scored?Number(home.score):null,awayScore:scored?Number(away.score):null,completed,live,venue:clean(c.venue?.fullName)||'Venue to be confirmed',league:'Premier League',status:event.status?.type?.detail||'',events:[],raw:event};}
 async function load(){const [fixtureResult,tableResult]=await Promise.all([fetch(`${api}/scoreboard?limit=1000&dates=${dateRange()}`),fetch('https://site.api.espn.com/apis/v2/sports/soccer/eng.1/standings').catch(()=>null)]);if(!fixtureResult.ok)throw Error(`The EPL feed is unavailable (${fixtureResult.status}).`);const json=await fixtureResult.json();const games=(json.events||[]).map(normalize).filter(Boolean);if(!games.length)throw Error('The EPL feed returned no fixtures for this period.');let ranks={};try{const table=tableResult&&tableResult.ok?await tableResult.json():null;const entries=table?.children?.flatMap(x=>x.standings?.entries||[])||[];entries.forEach(e=>{const rank=e.stats?.find(s=>s.name==='rank')?.value;if(Number.isFinite(rank))ranks[clean(e.team?.displayName)]=rank})}catch(e){console.info('Live table context was not available; upcoming scores remain deliberately neutral.')};games.forEach(g=>{const h=ranks[g.home],a=ranks[g.away];if(Number.isFinite(h)&&Number.isFinite(a)){const competitiveness=100-Math.min(70,Math.abs(h-a)*7);const highStakes=(h<=6&&a<=6)?20:(h>=15&&a>=15)?12:0;g.contextScore=Math.round(Math.min(100,competitiveness+highStakes))}});return games}
 async function enrich(g,{refresh=false}={}){if(g._enriched&&!refresh)return g;try{const r=await fetch(`${api}/summary?event=${g.id}`);if(!r.ok)return g;const j=await r.json(),plays=j.keyEvents||j.plays||[],competition=j.header?.competitions?.[0],status=competition?.status||j.header?.status,competitors=competition?.competitors||[];if(status){g.status=status.type?.detail||status.displayClock||g.status;g.completed=status.type?.completed===true;g.live=status.type?.state==='in'||status.type?.name==='STATUS_IN_PROGRESS'}competitors.forEach(team=>{if(team.homeAway==='home'&&team.score!=null)g.homeScore=Number(team.score);if(team.homeAway==='away'&&team.score!=null)g.awayScore=Number(team.score)});g.summary=j;g.injuries=j.injuries||[];g.rosters=j.rosters||[];g.events=plays.map(p=>{const text=clean(p.text||p.shortText),clock=String(p.clock?.displayValue||''),teamId=String(p.team?.id||p.participants?.[0]?.team?.id||'');const minute=Number((clock||text).match(/\d+/)?.[0]),type=/goal/i.test(text)?'goal':/red card/i.test(text)?'red':/yellow card/i.test(text)?'yellow':/penalty/i.test(text)?'penalty':/substitution/i.test(text)?'sub':'other';return {type,minute:Number.isFinite(minute)?minute:null,stoppage:/(?:45|90)\+\d+/.test(clock)||/(?:45|90)\+\d+/.test(text),text,teamId,scorer:clean(p.participants?.[0]?.athlete?.displayName),assist:clean(p.assist?.athlete?.displayName),ownGoal:/own goal/i.test(text)};});g.redCards=g.events.filter(x=>x.type==='red').length;g.penalties=g.events.filter(x=>x.type==='penalty').length;g.ownGoals=g.events.filter(x=>x.ownGoal).length;const by={};g.events.filter(x=>x.type==='goal'&&x.scorer).forEach(x=>by[x.scorer]=(by[x.scorer]||0)+1);g.events.forEach(x=>{if(x.type==='goal'&&by[x.scorer]>=3)x.hatTrick=true;if(x.type==='goal'&&by[x.scorer]>=2)x.multiGoal=true});g._enriched=true}catch(e){console.warn('Could not enrich match',e)}return g}
 function validation(games){const names=['Chelsea 4–3 Brighton','Manchester United 5–2 Ipswich','Leeds 1–1 Brentford','Sunderland 1–0 Fulham','Aston Villa 0–1 Arsenal'];const rows=names.map(name=>{const m=name.match(/^(.*?) (\d+)[–-](\d+) (.*)$/),g=games.find(x=>x.home===m[1]&&x.away===m[4]&&x.homeScore==m[2]&&x.awayScore==m[3]);const s=g&&WatchScore.score(g);return {Game:name,Total:s?.watchScore??'not in loaded live window',Drama:s?.drama??'—',Action:s?.action??'—',Exceptional:s?.exceptional??'—','Surprise/Context':s?.surpriseContext??'—'}});console.group('Must Watch validation — live provider data');console.table(rows);console.info('Available fields: final score always on completed fixtures; goals/scorers/minutes/cards/penalties/own goals only when ESPN summary supplies key events; assists, shots/SOT and pre-match context are not assumed.');console.groupEnd()}
 return {load,enrich,validation};
})();
